# Generated by Django 5.0.1 on 2024-01-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Honors_awards',
            new_name='HonorsAwards',
        ),
    ]
